-- Generated by nwg-displays on 2026-09-19 at 14:24:55. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@240.0",
    position = "1920x0",
    scale = 1.0,
    bitdepth = 10,
    vrr = 0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1,
    vrr = 0
})
