windowrule {
	name = jetbrain pop up
	match:initial_class = ^jetbrains-.+
	match:float = 1
	center = 1
	focus_on_activate = 1
}

windowrule {
  name = steam friend list
  match:initial_class = steam
  match:title = Friends List
  float = 1
}

windowrule = match:class ^(dota2)$, tag +games, content game
windowrule = match:class ^(awakened-poe-trade)$, tag +apt
windowrule = match:tag apt, float 1, no_blur 1, no_shadow 1, border_size 0, pin 1, size 100% 100%, center 1



# Window rules for HyprEmoji
windowrule = float true, match:title ^(HyprEmoji)$
windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.05)), match:title ^(HyprEmoji)$
