$background = rgb(000006)
$foreground = rgb(F7F5F7)
$color0 = rgb(111216)
$color1 = rgb(373F4D)
$color2 = rgb(3B4151)
$color3 = rgb(675C7E)
$color4 = rgb(AE3E71)
$color5 = rgb(76668E)
$color6 = rgb(AEAAAE)
$color7 = rgb(EBE9EB)
$color8 = rgb(A4A3A5)
$color9 = rgb(4A5467)
$color10 = rgb(4F576C)
$color11 = rgb(897BA7)
$color12 = rgb(E85397)
$color13 = rgb(9E88BD)
$color14 = rgb(E8E3E8)
$color15 = rgb(EBE9EB)
