# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131823)
$foreground = rgb(D7D8D9)
$color0 = rgb(A7A8AA)
$color1 = rgb(BBABAF)
$color2 = rgb(B3979A)
$color3 = rgb(893C42)
$color4 = rgb(222931)
$color5 = rgb(212930)
$color6 = rgb(192126)
$color7 = rgb(706769)
$color8 = rgb(AEA0A3)
$color9 = rgb(F9E4EA)
$color10 = rgb(EFCACD)
$color11 = rgb(B75158)
$color12 = rgb(2E3741)
$color13 = rgb(2C3640)
$color14 = rgb(222B33)
$color15 = rgb(F3E9EC)
