# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(05000A)
$foreground = rgb(AEE1F8)
$color0 = rgb(05000A)
$color1 = rgb(31213F)
$color2 = rgb(332545)
$color3 = rgb(3F4A7E)
$color4 = rgb(6C3892)
$color5 = rgb(455D9A)
$color6 = rgb(127EB1)
$color7 = rgb(83CBED)
$color8 = rgb(5C8EA6)
$color9 = rgb(422C54)
$color10 = rgb(44315C)
$color11 = rgb(5463A8)
$color12 = rgb(904AC2)
$color13 = rgb(5C7CCD)
$color14 = rgb(18A8EC)
$color15 = rgb(83CBED)
